load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "capi_registration_test",
    srcs = ["CAPIRegistrationTest.cpp"],
    deps = [
        "//mlir/dialects/cute_ir/lib/CAPI:cute",
        "//mlir/dialects/cute_ir/lib/CAPI:cute_nvgpu",
        "@llvm-project//mlir:CAPIIR",
    ],
)
