load("@rules_zig//zig:defs.bzl", "zig_binary")

zig_binary(
    name = "qwen",
    main = "main.zig",
    deps = [
        "@zml//zml",
    ],
)

zig_binary(
    name = "torch2zml",
    srcs = [
        "blocks.zig",
        "compiler.zig",
        "testing.zig",
        "torch2zml.zig",
    ],
    main = "torch2zml.zig",
    deps = [
        "@zml//stdx",
        "@zml//zml",
    ],
)
