const std = @import("std");

const Config = struct {
    execroot: []const u8,
    name: []const u8,
    target: []const u8,
    optimize: []const u8,
    modules: []const Module,
    linker: []const u8,
    link_args: []const []const u8,
    link_env: []const EnvironmentVariable,

    const Module = struct {
        name: []const u8,
        source: []const u8,
        deps: []const Dependency,
    };

    const Dependency = struct {
        name: []const u8,
        module: []const u8,
    };

    const EnvironmentVariable = struct {
        key: []const u8,
        value: []const u8,
    };
};

pub fn build(b: *std.Build) void {
    const config_path = b.option(
        []const u8,
        "bazel-config",
        "Path to the configuration generated by //:zig-build-prepare",
    ) orelse @panic("missing -Dbazel-config; run `bazel run //:zig-build-prepare -- <zig_binary label>` first");

    const config_bytes = std.Io.Dir.cwd().readFileAlloc(
        b.graph.io,
        config_path,
        b.allocator,
        .limited(128 * 1024 * 1024),
    ) catch |err|
        std.debug.panic("unable to read Bazel configuration '{s}': {s}", .{ config_path, @errorName(err) });
    const parsed = std.json.parseFromSlice(Config, b.allocator, config_bytes, .{}) catch |err|
        std.debug.panic("unable to parse Bazel configuration '{s}': {s}", .{ config_path, @errorName(err) });
    const config = parsed.value;

    const target_query = std.Build.parseTargetQuery(.{ .arch_os_abi = config.target }) catch
        std.debug.panic("Bazel supplied an unsupported Zig target '{s}'", .{config.target});
    const target = b.resolveTargetQuery(target_query);
    const optimize: std.builtin.OptimizeMode = std.meta.stringToEnum(std.builtin.OptimizeMode, config.optimize) orelse
        std.debug.panic("Bazel supplied an unsupported optimization mode '{s}'", .{config.optimize});
    const use_lld = b.option(
        bool,
        "use-lld",
        "Use LLD for Zig's static library link step",
    ) orelse !target.result.os.tag.isDarwin();

    const modules = b.allocator.alloc(*std.Build.Module, config.modules.len) catch @panic("OOM");
    var module_by_name: std.StringHashMapUnmanaged(*std.Build.Module) = .empty;
    for (config.modules, modules) |module_config, *module| {
        module.* = b.createModule(.{
            .root_source_file = .{ .cwd_relative = absolute(config.execroot, module_config.source, b) },
            .target = target,
            .optimize = optimize,
        });
        module_by_name.put(b.allocator, module_config.name, module.*) catch @panic("OOM");
    }
    for (config.modules, modules) |module_config, module| {
        for (module_config.deps) |dependency| {
            const imported = module_by_name.get(dependency.module) orelse
                std.debug.panic("Bazel module '{s}' imports missing module '{s}'", .{ module_config.name, dependency.module });
            module.addImport(dependency.name, imported);
        }
    }

    const library = b.addLibrary(.{
        .name = config.name,
        .root_module = modules[0],
        .linkage = .static,
        .use_llvm = true,
        .use_lld = use_lld,
    });
    library.bundle_compiler_rt = true;
    modules[0].link_libc = true;

    const link = b.addSystemCommand(&.{absolute(config.execroot, config.linker, b)});
    link.setCwd(.{ .cwd_relative = config.execroot });
    for (config.link_env) |env| {
        link.setEnvironmentVariable(env.key, env.value);
    }
    var output: ?std.Build.LazyPath = null;
    for (config.link_args) |arg| {
        if (std.mem.eql(u8, arg, "$ZIG_ARCHIVE")) {
            link.addArtifactArg(library);
        } else if (std.mem.eql(u8, arg, "$OUTPUT")) {
            output = link.addOutputFileArg(config.name);
        } else {
            link.addArg(arg);
        }
    }

    const binary = output orelse @panic("Bazel link command has no $OUTPUT placeholder");
    b.getInstallStep().dependOn(&b.addInstallBinFile(binary, config.name).step);
}

fn absolute(execroot: []const u8, path: []const u8, b: *std.Build) []const u8 {
    if (std.fs.path.isAbsolute(path)) return path;
    return b.pathJoin(&.{ execroot, path });
}
