load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cute",
    srcs = [
        "Cute.cpp",
        "CuteAttributes.cpp",
        "CuteCompilerAttributes.cpp",
        "CuteTypes.cpp",
    ],
    deps = [
        "//mlir/dialects/cute_ir/include/cute_ir-c/Dialect:cute",
        "//mlir/dialects/cute_ir/lib/Dialect/IR:dialect",
        "@llvm-project//mlir:CAPIIR",
    ],
    alwayslink = True,
)

cc_library(
    name = "cute_nvgpu",
    srcs = [
        "CuteNVGPU.cpp",
        "CuteNVGPUAttributes.cpp",
        "CuteNVGPUTypes.cpp",
    ],
    deps = [
        "//mlir/dialects/cute_ir/include/cute_ir-c/Dialect:cute_nvgpu",
        "//mlir/dialects/cute_ir/lib/Dialect/CuteNVGPU/IR:dialect",
        "@llvm-project//mlir:CAPIIR",
    ],
    alwayslink = True,
)

cc_library(
    name = "cuda",
    srcs = [
        "Cuda.cpp",
        "CudaAttributes.cpp",
        "CudaTypes.cpp",
    ],
    deps = [
        "//mlir/dialects/cute_ir/include/cute_ir-c/Dialect:cuda",
        "//mlir/dialects/cute_ir/lib/Dialect/Cuda/IR:dialect",
        "@llvm-project//mlir:CAPIIR",
    ],
    alwayslink = True,
)

cc_library(
    name = "nvvm",
    srcs = [
        "NVVM.cpp",
        "NVVMAttributes.cpp",
    ],
    deps = [
        "//mlir/dialects/cute_ir/include/cute_ir-c/Dialect:nvvm",
        "//mlir/dialects/cute_ir/lib/Dialect/NVVM/IR:dialect",
        "@llvm-project//mlir:CAPIIR",
    ],
    alwayslink = True,
)
