load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_test")

zig_binary(
    name = "detokenization",
    srcs = [
        "algebra.zig",
        "attention.zig",
        "gemma/base.zig",
        "gemma/gemma.zig",
        "gemma/inference.zig",
        "graph.zig",
        "inference.zig",
        "kmeans.zig",
        "llm.zig",
        "main.zig",
        "model.zig",
        "productq.zig",
        "quantization.zig",
        "sampling.zig",
        "saveload.zig",
        "tokens.zig",
    ],
    main = "main.zig",
    visibility = ["//visibility:public"],
    deps = [
        "//bazel",
        "//mlir",
        "//mlir/dialects",
        "//zml",
    ],
)