#!/usr/bin/env python3

import pathlib
import re
import shlex
import subprocess
import sys


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: gen_lldb_bazel_source_map.py <binary> <workspace_root> <output_file>",
            file=sys.stderr,
        )
        return 2

    binary = pathlib.Path(sys.argv[1]).resolve()
    workspace_root = pathlib.Path(sys.argv[2]).resolve()
    output_file = pathlib.Path(sys.argv[3]).resolve()
    execroot_link = workspace_root / "bazel-zml"
    if not execroot_link.exists():
        print(f"missing Bazel execroot symlink: {execroot_link}", file=sys.stderr)
        return 1

    result = subprocess.run(
        ["lldb", "--batch", "-o", "image lookup -vn main.main", str(binary)],
        check=True,
        capture_output=True,
        text=True,
    )
    match = re.search(
        r"LineEntry: \[[^\]]+\): (.*?/execroot/_main)/.*:\d+",
        result.stdout,
    )
    if match is None:
        print(
            "failed to locate Bazel execroot source path in LLDB output",
            file=sys.stderr,
        )
        return 1

    execroot_prefix = pathlib.Path(match.group(1))
    actual_execroot = execroot_link.resolve()

    # Some step events still surface the raw sandbox path. Create that path as a
    # symlink to the real execroot so VS Code can open the same sources.
    if not execroot_prefix.exists():
        execroot_prefix.parent.mkdir(parents=True, exist_ok=True)
        execroot_prefix.symlink_to(actual_execroot, target_is_directory=True)

    output_file.write_text(
        "\n".join(
            [
                "# Generated by .vscode/gen_lldb_bazel_source_map.py",
                "settings clear target.source-map",
                "settings set target.source-map "
                f"{shlex.quote(str(execroot_prefix))} {shlex.quote(str(workspace_root))}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
