load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_test")

zig_binary(
    name = "minimax_h3",
    srcs = glob(["**/*.zig"]),
    main = "main.zig",
    visibility = ["//visibility:public"],
    deps = ["//zml"],
)

zig_binary(
    name = "taehv_check",
    srcs = glob(["**/*.zig"]),
    main = "taehv_check.zig",
    visibility = ["//visibility:public"],
    deps = ["//zml"],
)

zig_test(
    name = "test",
    srcs = glob(["**/*.zig"]),
    main = "tests.zig",
    visibility = ["//visibility:public"],
    deps = ["//zml"],
)

build_test(
    name = "compile",
    targets = [
        ":minimax_h3",
        ":test",
    ],
)
