load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cute",
    hdrs = ["Cute.h"],
    strip_include_prefix = "/mlir/dialects/cute_ir/include",
)

cc_library(
    name = "cute_nvgpu",
    hdrs = ["CuteNVGPU.h"],
    strip_include_prefix = "/mlir/dialects/cute_ir/include",
)
