/// OutputProjection parity checker.
///
/// Verifies the ZML OutputProjection (scale_shift_table + layernorm + proj_out)
/// matches the Python reference fixture generated by export_output_projection_fixture.py.
///
/// Usage:
///   bazel run //examples/ltx:output_projection_check -- \
///       /root/models/ltx-2.3/ltx-2.3-22b-distilled.safetensors \
///       /root/repos/LTX-2/trace_run/output_projection_fixture.safetensors

const std = @import("std");
const zml = @import("zml");
const model = @import("model.zig");
const check_utils = @import("check_utils.zig");

comptime {
    @setEvalBranchQuota(20000);
}

pub const std_options: std.Options = .{ .log_level = .info };

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    std.log.info("OutputProjection parity checker", .{});

    var it = init.minimal.args.iterate();
    _ = it.next(); // exe

    const ckpt_path = it.next() orelse {
        std.log.err("Usage: output_projection_check <checkpoint.safetensors> <fixture.safetensors>", .{});
        return error.InvalidArgs;
    };
    const fixture_path = it.next() orelse {
        std.log.err("Usage: output_projection_check <checkpoint.safetensors> <fixture.safetensors>", .{});
        return error.InvalidArgs;
    };

    var ckpt_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, ckpt_path) catch |err| {
        std.log.err("Failed to open checkpoint: {s}", .{ckpt_path});
        return err;
    };
    defer ckpt_reg.deinit();
    var ckpt_store: zml.io.TensorStore = .fromRegistry(allocator, &ckpt_reg);
    defer ckpt_store.deinit();

    var fix_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, fixture_path) catch |err| {
        std.log.err("Failed to open fixture: {s}", .{fixture_path});
        return err;
    };
    defer fix_reg.deinit();
    var fix_store: zml.io.TensorStore = .fromRegistry(allocator, &fix_reg);
    defer fix_store.deinit();

    const platform: *zml.Platform = try .auto(allocator, io, .{});
    defer platform.deinit(allocator);
    const sharding = try zml.sharding.replicatedSharding(platform);

    // Root strips model.diffusion_model etc.
    const root = model.selectTransformerRoot(ckpt_store.view());

    var passes: usize = 0;
    var failures: usize = 0;

    if (checkStream(
        allocator, io, platform, sharding,
        root, &ckpt_store, &fix_store,
        "video", "scale_shift_table", "proj_out",
    )) |ok| {
        if (ok) passes += 1 else failures += 1;
    } else |err| {
        std.log.err("video raised error: {}", .{err});
        failures += 1;
    }

    if (checkStream(
        allocator, io, platform, sharding,
        root, &ckpt_store, &fix_store,
        "audio", "audio_scale_shift_table", "audio_proj_out",
    )) |ok| {
        if (ok) passes += 1 else failures += 1;
    } else |err| {
        std.log.err("audio raised error: {}", .{err});
        failures += 1;
    }

    std.log.info("Results: {d} passed, {d} failed", .{ passes, failures });
    if (failures > 0) return error.ParityCheckFailed;
}

fn checkStream(
    allocator: std.mem.Allocator,
    io: std.Io,
    platform: *zml.Platform,
    sharding: zml.sharding.Sharding,
    root: zml.io.TensorStore.View,
    ckpt_store: *zml.io.TensorStore,
    fix_store: *zml.io.TensorStore,
    comptime label: []const u8,
    comptime sst_key: []const u8,
    comptime proj_prefix: []const u8,
) !bool {
    std.log.info("--- Checking {s} output projection ---", .{label});

    var x_buf = try check_utils.loadBufferFromStore(
        allocator, io, platform, fix_store, label ++ ".x", sharding,
    );
    defer x_buf.deinit();
    var emb_buf = try check_utils.loadBufferFromStore(
        allocator, io, platform, fix_store, label ++ ".embedded_timestep", sharding,
    );
    defer emb_buf.deinit();
    var ref_buf = try check_utils.loadBufferFromStore(
        allocator, io, platform, fix_store, label ++ ".output", sharding,
    );
    defer ref_buf.deinit();

    var params_shape = model.OutputProjection.Params{
        .scale_shift_table = root.createTensor(sst_key, .{ .n_ssv, .d }, null),
        .proj_out = .init(
            root.withPrefix(proj_prefix).createTensor("weight", .{ .d_out, .d }, null),
            root.withPrefix(proj_prefix).createTensor("bias", .{.d_out}, null),
            .d,
        ),
    };

    const x_s = zml.Tensor.fromShape(x_buf.shape()).withPartialTags(.{ .b, .t, .d });
    const emb_s = zml.Tensor.fromShape(emb_buf.shape()).withPartialTags(.{ .b, .d_emb });

    std.log.info("  Compiling forward graph...", .{});
    var exe = try platform.compileFn(
        allocator, io,
        model.forwardOutputProjection,
        .{ x_s, emb_s, params_shape },
        .{ .shardings = &.{sharding} },
    );
    defer exe.deinit();
    std.log.info("  Compilation done", .{});

    std.log.info("  Loading weights...", .{});
    var params_bufs = try zml.io.load(model.OutputProjection.Params, &params_shape, allocator, io, platform, .{
        .store = ckpt_store,
        .shardings = &.{sharding},
        .parallelism = 4,
        .dma_chunks = 4,
        .dma_chunk_size = 16 * zml.MiB,
    });
    defer model.OutputProjection.Params.unloadBuffers(&params_bufs);
    std.log.info("  Weights loaded", .{});

    var args = try exe.args(allocator);
    defer args.deinit(allocator);
    var results = try exe.results(allocator);
    defer results.deinit(allocator);

    args.set(.{ x_buf, emb_buf, params_bufs });
    exe.call(args, &results);

    var output_buf = results.get(zml.Buffer);
    defer output_buf.deinit();

    const metrics = check_utils.compareBuffersExtended(io, output_buf, ref_buf, 0.15, 0.02) catch |err| {
        std.log.err("  comparison failed: {}", .{err});
        return false;
    };
    const passed = metrics.close_fraction >= 0.999 and metrics.mean_abs_error < 0.1;

    std.log.info("  output:  mean_abs={d:.5}  max_abs={d:.5}  cos_sim={d:.6}  close={d:.4}", .{
        metrics.mean_abs_error,
        metrics.max_abs_error,
        metrics.cosine_similarity,
        metrics.close_fraction,
    });

    if (passed) {
        std.log.info("  {s}: PASSED", .{label});
    } else {
        std.log.err("  {s}: FAILED", .{label});
    }
    return passed;
}
