/// AdaLayerNormSingle parity checker.
///
/// Verifies all 8 adaln_single modules match the Python reference fixture
/// generated by export_adaln_single_fixture.py.
///
/// Usage:
///   bazel run //examples/ltx:adaln_single_check -- \
///       /root/models/ltx-2.3/ltx-2.3-22b-distilled.safetensors \
///       /root/repos/LTX-2/trace_run/adaln_single_fixture.safetensors

const std = @import("std");
const zml = @import("zml");
const model = @import("model.zig");
const check_utils = @import("check_utils.zig");

comptime {
    @setEvalBranchQuota(20000);
}

pub const std_options: std.Options = .{
    .log_level = .info,
};

const ModuleDesc = struct {
    fix_prefix: []const u8, // prefix used in fixture keys
    ckpt_suffix: []const u8, // suffix under diffusion_model root
};

const MODULES = [_]ModuleDesc{
    .{ .fix_prefix = "adaln_single", .ckpt_suffix = "adaln_single" },
    .{ .fix_prefix = "audio_adaln_single", .ckpt_suffix = "audio_adaln_single" },
    .{ .fix_prefix = "prompt_adaln_single", .ckpt_suffix = "prompt_adaln_single" },
    .{ .fix_prefix = "audio_prompt_adaln_single", .ckpt_suffix = "audio_prompt_adaln_single" },
    .{ .fix_prefix = "av_ca_video_scale_shift_adaln_single", .ckpt_suffix = "av_ca_video_scale_shift_adaln_single" },
    .{ .fix_prefix = "av_ca_audio_scale_shift_adaln_single", .ckpt_suffix = "av_ca_audio_scale_shift_adaln_single" },
    .{ .fix_prefix = "av_ca_a2v_gate_adaln_single", .ckpt_suffix = "av_ca_a2v_gate_adaln_single" },
    .{ .fix_prefix = "av_ca_v2a_gate_adaln_single", .ckpt_suffix = "av_ca_v2a_gate_adaln_single" },
};

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    std.log.info("AdaLayerNormSingle parity checker", .{});

    var it = init.minimal.args.iterate();
    _ = it.next(); // exe

    const ckpt_path = it.next() orelse {
        std.log.err("Usage: adaln_single_check <full_checkpoint.safetensors> <fixture.safetensors>", .{});
        return error.InvalidArgs;
    };
    const fixture_path = it.next() orelse {
        std.log.err("Usage: adaln_single_check <full_checkpoint.safetensors> <fixture.safetensors>", .{});
        return error.InvalidArgs;
    };

    // Load checkpoint
    var ckpt_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, ckpt_path) catch |err| {
        std.log.err("Failed to open checkpoint: {s}", .{ckpt_path});
        return err;
    };
    defer ckpt_reg.deinit();
    var ckpt_store: zml.io.TensorStore = .fromRegistry(allocator, &ckpt_reg);
    defer ckpt_store.deinit();

    // Load fixture
    var fix_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, fixture_path) catch |err| {
        std.log.err("Failed to open fixture: {s}", .{fixture_path});
        return err;
    };
    defer fix_reg.deinit();
    var fix_store: zml.io.TensorStore = .fromRegistry(allocator, &fix_reg);
    defer fix_store.deinit();

    const platform: *zml.Platform = try .auto(allocator, io, .{});
    defer platform.deinit(allocator);
    const sharding = try zml.sharding.replicatedSharding(platform);

    // Root view strips model.diffusion_model etc.
    const root = model.selectTransformerRoot(ckpt_store.view());

    var passes: usize = 0;
    var failures: usize = 0;

    inline for (MODULES) |m| {
        if (runModuleCheck(allocator, io, platform, sharding, root, &ckpt_store, &fix_store, m)) |ok| {
            if (ok) passes += 1 else failures += 1;
        } else |err| {
            std.log.err("Module {s} raised error: {}", .{ m.fix_prefix, err });
            failures += 1;
        }
    }

    std.log.info("Results: {d} passed, {d} failed", .{ passes, failures });
    if (failures > 0) return error.ParityCheckFailed;
}

fn loadBuf(
    allocator: std.mem.Allocator,
    io: std.Io,
    platform: *zml.Platform,
    store: *zml.io.TensorStore,
    key: []const u8,
    sharding: zml.sharding.Sharding,
) !zml.Buffer {
    return check_utils.loadBufferFromStore(allocator, io, platform, store, key, sharding) catch |err| {
        std.log.err("Missing fixture key: {s}", .{key});
        return err;
    };
}

fn runModuleCheck(
    allocator: std.mem.Allocator,
    io: std.Io,
    platform: *zml.Platform,
    sharding: zml.sharding.Sharding,
    root: zml.io.TensorStore.View,
    ckpt_store: *zml.io.TensorStore,
    fix_store: *zml.io.TensorStore,
    comptime m: ModuleDesc,
) !bool {
    std.log.info("--- Checking {s} ---", .{m.fix_prefix});

    var sigma_buf = try loadBuf(allocator, io, platform, fix_store, m.fix_prefix ++ ".sigma_scaled", sharding);
    defer sigma_buf.deinit();
    var mod_ref_buf = try loadBuf(allocator, io, platform, fix_store, m.fix_prefix ++ ".modulation", sharding);
    defer mod_ref_buf.deinit();
    var emb_ts_ref_buf = try loadBuf(allocator, io, platform, fix_store, m.fix_prefix ++ ".embedded_timestep", sharding);
    defer emb_ts_ref_buf.deinit();

    // sigma shape from fixture: [4] f32. sinusoidalTimestepEmbedding tags it .b internally.
    const sigma_tensor = zml.Tensor.fromShape(sigma_buf.shape());

    var params_shape = model.AdaLayerNormSingle.initParams(root.withPrefix(m.ckpt_suffix));

    std.log.info("  Compiling forward graph...", .{});
    var exe = try platform.compileFn(
        allocator,
        io,
        model.forwardAdalnSingle,
        .{ sigma_tensor, params_shape },
        .{ .shardings = &.{sharding} },
    );
    defer exe.deinit();
    std.log.info("  Compilation done", .{});

    std.log.info("  Loading weights...", .{});
    var params_bufs = try zml.io.load(model.AdaLayerNormSingle.Params, &params_shape, allocator, io, platform, .{
        .store = ckpt_store,
        .shardings = &.{sharding},
        .parallelism = 4,
        .dma_chunks = 4,
        .dma_chunk_size = 16 * zml.MiB,
    });
    defer model.AdaLayerNormSingle.Params.unloadBuffers(&params_bufs);
    std.log.info("  Weights loaded", .{});

    var args = try exe.args(allocator);
    defer args.deinit(allocator);
    var results = try exe.results(allocator);
    defer results.deinit(allocator);

    args.set(.{ sigma_buf, params_bufs });
    exe.call(args, &results);

    const AdalnResults = struct {
        modulation: zml.Buffer,
        embedded_timestep: zml.Buffer,
    };
    const out = results.get(AdalnResults);
    defer {
        var mb = out.modulation;
        mb.deinit();
        var eb = out.embedded_timestep;
        eb.deinit();
    }

    const mod_stats = check_utils.compareBuffersExtended(io, out.modulation, mod_ref_buf, 0.15, 0.02) catch |err| {
        std.log.err("  modulation comparison failed: {}", .{err});
        return false;
    };
    const emb_stats = check_utils.compareBuffersExtended(io, out.embedded_timestep, emb_ts_ref_buf, 0.15, 0.02) catch |err| {
        std.log.err("  embedded_timestep comparison failed: {}", .{err});
        return false;
    };

    const mod_ok = mod_stats.close_fraction >= 0.999 and mod_stats.mean_abs_error < 0.1;
    const emb_ok = emb_stats.close_fraction >= 0.999 and emb_stats.mean_abs_error < 0.1;

    std.log.info("  modulation:        mean_abs={d:.5}  max_abs={d:.5}  cos_sim={d:.6}  close={d:.4}", .{
        mod_stats.mean_abs_error, mod_stats.max_abs_error, mod_stats.cosine_similarity, mod_stats.close_fraction,
    });
    std.log.info("  embedded_timestep: mean_abs={d:.5}  max_abs={d:.5}  cos_sim={d:.6}  close={d:.4}", .{
        emb_stats.mean_abs_error, emb_stats.max_abs_error, emb_stats.cosine_similarity, emb_stats.close_fraction,
    });

    if (mod_ok and emb_ok) {
        std.log.info("  {s}: PASSED", .{m.fix_prefix});
        return true;
    } else {
        std.log.err("  {s}: FAILED (mod_ok={} emb_ok={})", .{ m.fix_prefix, mod_ok, emb_ok });
        return false;
    }
}
