/// Full velocity_model step parity checker.
///
/// Validates the full transformer step (48 blocks + output projection) against
/// the live-capture fixture generated by export_live_capture_fixture.py.
///
/// Compiles a single-block exe and loops 48 times (swapping weights each
/// iteration), then runs the output projection. This avoids the MLIR
/// argument-count limit (~1024) that a monolithic 48-block function would hit.
///
/// Usage:
///   bazel run //examples/ltx:full_step_check -- \
///       /root/models/ltx-2.3/ltx-2.3-22b-distilled.safetensors \
///       /root/repos/LTX-2/trace_run/live_capture_fixture_step_000_t512.safetensors

const std = @import("std");
const zml = @import("zml");
const model = @import("model.zig");
const check_utils = @import("check_utils.zig");

comptime {
    @setEvalBranchQuota(200000);
}

pub const std_options: std.Options = .{ .log_level = .info };

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    std.log.info("Full velocity_model step parity checker", .{});

    var it = init.minimal.args.iterate();
    _ = it.next(); // exe

    const ckpt_path = it.next() orelse {
        std.log.err("Usage: full_step_check <checkpoint.safetensors> <live_capture_fixture.safetensors>", .{});
        return error.InvalidArgs;
    };
    const fixture_path = it.next() orelse {
        std.log.err("Usage: full_step_check <checkpoint.safetensors> <live_capture_fixture.safetensors>", .{});
        return error.InvalidArgs;
    };

    // Open checkpoint
    var ckpt_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, ckpt_path) catch |err| {
        std.log.err("Failed to open checkpoint: {s}", .{ckpt_path});
        return err;
    };
    defer ckpt_reg.deinit();
    var ckpt_store: zml.io.TensorStore = .fromRegistry(allocator, &ckpt_reg);
    defer ckpt_store.deinit();

    // Open fixture
    var fix_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, fixture_path) catch |err| {
        std.log.err("Failed to open fixture: {s}", .{fixture_path});
        return err;
    };
    defer fix_reg.deinit();
    var fix_store: zml.io.TensorStore = .fromRegistry(allocator, &fix_reg);
    defer fix_store.deinit();

    const platform: *zml.Platform = try .auto(allocator, io, .{});
    defer platform.deinit(allocator);
    const sharding = try zml.sharding.replicatedSharding(platform);

    // Load fixture tensors
    std.log.info("Loading fixture tensors...", .{});

    // Stream inputs (post-patchify)
    var vx_in_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.vx_in", sharding);
    defer vx_in_buf.deinit();
    var ax_in_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.ax_in", sharding);
    defer ax_in_buf.deinit();

    // Timestep modulations
    var video_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.video_timesteps", sharding);
    defer video_ts_buf.deinit();
    var audio_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.audio_timesteps", sharding);
    defer audio_ts_buf.deinit();
    var v_prompt_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v_prompt_timestep", sharding);
    defer v_prompt_ts_buf.deinit();
    var a_prompt_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a_prompt_timestep", sharding);
    defer a_prompt_ts_buf.deinit();

    // PE cos/sin
    var v_pe_cos_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v_pe_cos", sharding);
    defer v_pe_cos_buf.deinit();
    var v_pe_sin_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v_pe_sin", sharding);
    defer v_pe_sin_buf.deinit();
    var a_pe_cos_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a_pe_cos", sharding);
    defer a_pe_cos_buf.deinit();
    var a_pe_sin_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a_pe_sin", sharding);
    defer a_pe_sin_buf.deinit();

    // Text contexts
    var v_text_ctx_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v_text_ctx", sharding);
    defer v_text_ctx_buf.deinit();
    var a_text_ctx_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a_text_ctx", sharding);
    defer a_text_ctx_buf.deinit();

    // AV cross-attn timestep embeddings
    var v_cross_ss_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v_cross_ss_ts", sharding);
    defer v_cross_ss_ts_buf.deinit();
    var v_cross_gate_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v_cross_gate_ts", sharding);
    defer v_cross_gate_ts_buf.deinit();
    var a_cross_ss_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a_cross_ss_ts", sharding);
    defer a_cross_ss_ts_buf.deinit();
    var a_cross_gate_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a_cross_gate_ts", sharding);
    defer a_cross_gate_ts_buf.deinit();

    // AV cross-attn PE
    var a2v_pe_cos_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a2v_pe_cos", sharding);
    defer a2v_pe_cos_buf.deinit();
    var a2v_pe_sin_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a2v_pe_sin", sharding);
    defer a2v_pe_sin_buf.deinit();
    var a2v_k_pe_cos_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a2v_k_pe_cos", sharding);
    defer a2v_k_pe_cos_buf.deinit();
    var a2v_k_pe_sin_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.a2v_k_pe_sin", sharding);
    defer a2v_k_pe_sin_buf.deinit();
    var v2a_pe_cos_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v2a_pe_cos", sharding);
    defer v2a_pe_cos_buf.deinit();
    var v2a_pe_sin_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v2a_pe_sin", sharding);
    defer v2a_pe_sin_buf.deinit();
    var v2a_k_pe_cos_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v2a_k_pe_cos", sharding);
    defer v2a_k_pe_cos_buf.deinit();
    var v2a_k_pe_sin_buf = try loadBuf(allocator, io, platform, &fix_store, "full_step.v2a_k_pe_sin", sharding);
    defer v2a_k_pe_sin_buf.deinit();

    // Embedded timestep for output projection (3D, batch-expanded)
    var v_emb_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "output_projection.video.embedded_timestep", sharding);
    defer v_emb_ts_buf.deinit();
    var a_emb_ts_buf = try loadBuf(allocator, io, platform, &fix_store, "output_projection.audio.embedded_timestep", sharding);
    defer a_emb_ts_buf.deinit();

    // Expected outputs — use output_projection.*.output (raw projection output),
    // NOT full_step.*_out (which includes the denoising formula applied by Python's forward()).
    var video_out_ref = try loadBuf(allocator, io, platform, &fix_store, "output_projection.video.output", sharding);
    defer video_out_ref.deinit();
    var audio_out_ref = try loadBuf(allocator, io, platform, &fix_store, "output_projection.audio.output", sharding);
    defer audio_out_ref.deinit();

    std.log.info("Fixture loaded. Shapes:", .{});
    std.log.info("  vx_in: {any}", .{vx_in_buf.shape()});
    std.log.info("  ax_in: {any}", .{ax_in_buf.shape()});
    std.log.info("  video_timesteps: {any}", .{video_ts_buf.shape()});
    std.log.info("  v_emb_ts: {any}", .{v_emb_ts_buf.shape()});
    std.log.info("  video_out_ref: {any}", .{video_out_ref.shape()});
    std.log.info("  audio_out_ref: {any}", .{audio_out_ref.shape()});

    // ---- Init param shapes for all 48 blocks + output projection ----
    // Heap-allocate: FullStepParams contains [48]Block0FullParams, too large for stack.
    std.log.info("Initializing model params...", .{});
    var params_shape = try allocator.create(model.FullStepParams);
    defer allocator.destroy(params_shape);
    params_shape.* = model.initFullStepParams(ckpt_store.view());

    // ---- Compile single-block exe ----
    std.log.info("Compiling single-block exe...", .{});
    var block_exe = try platform.compileFn(
        allocator, io,
        model.forwardBlock0Native,
        .{
            zml.Tensor.fromShape(vx_in_buf.shape()),
            zml.Tensor.fromShape(ax_in_buf.shape()),
            zml.Tensor.fromShape(video_ts_buf.shape()),
            zml.Tensor.fromShape(audio_ts_buf.shape()),
            zml.Tensor.fromShape(v_prompt_ts_buf.shape()),
            zml.Tensor.fromShape(a_prompt_ts_buf.shape()),
            zml.Tensor.fromShape(v_pe_cos_buf.shape()),
            zml.Tensor.fromShape(v_pe_sin_buf.shape()),
            zml.Tensor.fromShape(a_pe_cos_buf.shape()),
            zml.Tensor.fromShape(a_pe_sin_buf.shape()),
            zml.Tensor.fromShape(v_text_ctx_buf.shape()),
            zml.Tensor.fromShape(a_text_ctx_buf.shape()),
            zml.Tensor.fromShape(v_cross_ss_ts_buf.shape()),
            zml.Tensor.fromShape(v_cross_gate_ts_buf.shape()),
            zml.Tensor.fromShape(a_cross_ss_ts_buf.shape()),
            zml.Tensor.fromShape(a_cross_gate_ts_buf.shape()),
            zml.Tensor.fromShape(a2v_pe_cos_buf.shape()),
            zml.Tensor.fromShape(a2v_pe_sin_buf.shape()),
            zml.Tensor.fromShape(a2v_k_pe_cos_buf.shape()),
            zml.Tensor.fromShape(a2v_k_pe_sin_buf.shape()),
            zml.Tensor.fromShape(v2a_pe_cos_buf.shape()),
            zml.Tensor.fromShape(v2a_pe_sin_buf.shape()),
            zml.Tensor.fromShape(v2a_k_pe_cos_buf.shape()),
            zml.Tensor.fromShape(v2a_k_pe_sin_buf.shape()),
            params_shape.blocks[0],
        },
        .{ .shardings = &.{sharding} },
    );
    defer block_exe.deinit();
    std.log.info("Single-block exe compiled.", .{});

    // ---- Compile output projection exe ----
    std.log.info("Compiling output projection exe...", .{});
    const x_v_s = zml.Tensor.fromShape(vx_in_buf.shape()).withPartialTags(.{ .b, .t, .d });
    const emb_v_s = zml.Tensor.fromShape(v_emb_ts_buf.shape()).withPartialTags(.{ .b, .d_emb });
    var proj_v_exe = try platform.compileFn(
        allocator, io,
        model.forwardOutputProjection,
        .{ x_v_s, emb_v_s, params_shape.norm_proj_out },
        .{ .shardings = &.{sharding} },
    );
    defer proj_v_exe.deinit();

    const x_a_s = zml.Tensor.fromShape(ax_in_buf.shape()).withPartialTags(.{ .b, .t, .d });
    const emb_a_s = zml.Tensor.fromShape(a_emb_ts_buf.shape()).withPartialTags(.{ .b, .d_emb });
    var proj_a_exe = try platform.compileFn(
        allocator, io,
        model.forwardOutputProjection,
        .{ x_a_s, emb_a_s, params_shape.audio_norm_proj_out },
        .{ .shardings = &.{sharding} },
    );
    defer proj_a_exe.deinit();
    std.log.info("Output projection exes compiled.", .{});

    // ---- Load all 48 block weights ----
    // Heap-allocate: 48 × Bufferized(Block0FullParams) is too large for the default stack.
    std.log.info("Loading 48 block weights...", .{});
    var block_params_bufs = try allocator.create([48]zml.Bufferized(model.Block0FullParams));
    defer allocator.destroy(block_params_bufs);
    for (0..48) |i| {
        block_params_bufs[i] = try zml.io.load(
            model.Block0FullParams,
            &params_shape.blocks[i],
            allocator, io, platform,
            .{
                .store = &ckpt_store,
                .shardings = &.{sharding},
                .parallelism = 4,
                .dma_chunks = 4,
                .dma_chunk_size = 16 * zml.MiB,
            },
        );
    }
    defer for (&block_params_bufs.*) |*bp| model.unloadBlock0FullBuffers(bp);
    std.log.info("Block weights loaded.", .{});

    // ---- Load output projection weights ----
    std.log.info("Loading output projection weights...", .{});
    var proj_v_bufs = try zml.io.load(
        model.OutputProjection.Params,
        &params_shape.norm_proj_out,
        allocator, io, platform,
        .{
            .store = &ckpt_store,
            .shardings = &.{sharding},
            .parallelism = 4,
            .dma_chunks = 4,
            .dma_chunk_size = 16 * zml.MiB,
        },
    );
    defer model.OutputProjection.Params.unloadBuffers(&proj_v_bufs);

    var proj_a_bufs = try zml.io.load(
        model.OutputProjection.Params,
        &params_shape.audio_norm_proj_out,
        allocator, io, platform,
        .{
            .store = &ckpt_store,
            .shardings = &.{sharding},
            .parallelism = 4,
            .dma_chunks = 4,
            .dma_chunk_size = 16 * zml.MiB,
        },
    );
    defer model.OutputProjection.Params.unloadBuffers(&proj_a_bufs);
    std.log.info("Output projection weights loaded.", .{});

    // ---- Run 48-block chain ----
    std.log.info("Running 48-block chain...", .{});
    var h_v = vx_in_buf;
    var h_a = ax_in_buf;

    for (0..48) |i| {
        var args = try block_exe.args(allocator);
        defer args.deinit(allocator);
        var results = try block_exe.results(allocator);
        defer results.deinit(allocator);

        args.set(.{
            h_v, h_a,
            video_ts_buf, audio_ts_buf,
            v_prompt_ts_buf, a_prompt_ts_buf,
            v_pe_cos_buf, v_pe_sin_buf,
            a_pe_cos_buf, a_pe_sin_buf,
            v_text_ctx_buf, a_text_ctx_buf,
            v_cross_ss_ts_buf, v_cross_gate_ts_buf,
            a_cross_ss_ts_buf, a_cross_gate_ts_buf,
            a2v_pe_cos_buf, a2v_pe_sin_buf,
            a2v_k_pe_cos_buf, a2v_k_pe_sin_buf,
            v2a_pe_cos_buf, v2a_pe_sin_buf,
            v2a_k_pe_cos_buf, v2a_k_pe_sin_buf,
            block_params_bufs[i],
        });
        block_exe.call(args, &results);

        const out = results.get(zml.Bufferized(model.BasicAVTransformerBlock.FullOutputs));

        // Free previous intermediates (but not the original fixture inputs)
        if (i > 0) {
            h_v.deinit();
            h_a.deinit();
        }
        h_v = out.vx_out;
        h_a = out.ax_out;

        if (i % 8 == 7 or i == 47) {
            std.log.info("  block {d:>2} done", .{i});
        }
    }
    std.log.info("48-block chain complete.", .{});

    // ---- Diagnostic: compare block chain output vs output_projection input ----
    {
        // Check if full_step.video_out == output_projection.video.output
        var proj_v_out_ref = try loadBuf(allocator, io, platform, &fix_store, "output_projection.video.output", sharding);
        defer proj_v_out_ref.deinit();
        const v_ref_cmp = check_utils.compareBuffersExtended(
            io, video_out_ref, proj_v_out_ref, 0.15, 0.02,
        ) catch |err| {
            std.log.err("full_step.video_out vs output_projection.video.output comparison failed: {}", .{err});
            return error.ParityCheckFailed;
        };
        logMetrics("DIAG video_out_ref vs proj.video.output", v_ref_cmp);

        var proj_v_x_ref = try loadBuf(allocator, io, platform, &fix_store, "output_projection.video.x_in", sharding);
        defer proj_v_x_ref.deinit();
        const v_chain_metrics = check_utils.compareBuffersExtended(
            io, h_v, proj_v_x_ref, 0.15, 0.02,
        ) catch |err| {
            std.log.err("Video chain vs proj x_in comparison failed: {}", .{err});
            return error.ParityCheckFailed;
        };
        logMetrics("DIAG video chain vs proj_x_in", v_chain_metrics);

        var proj_a_x_ref = try loadBuf(allocator, io, platform, &fix_store, "output_projection.audio.x_in", sharding);
        defer proj_a_x_ref.deinit();
        const a_chain_metrics = check_utils.compareBuffersExtended(
            io, h_a, proj_a_x_ref, 0.15, 0.02,
        ) catch |err| {
            std.log.err("Audio chain vs proj x_in comparison failed: {}", .{err});
            return error.ParityCheckFailed;
        };
        logMetrics("DIAG audio chain vs proj_x_in", a_chain_metrics);

        // Run output projection on fixture's x_in to isolate whether the issue is
        // in the projection itself vs the chain output.
        {
            var diag_v_args = try proj_v_exe.args(allocator);
            defer diag_v_args.deinit(allocator);
            var diag_v_results = try proj_v_exe.results(allocator);
            defer diag_v_results.deinit(allocator);
            diag_v_args.set(.{ proj_v_x_ref, v_emb_ts_buf, proj_v_bufs });
            proj_v_exe.call(diag_v_args, &diag_v_results);
            var diag_v_out = diag_v_results.get(zml.Buffer);
            defer diag_v_out.deinit();

            const diag_v_m = check_utils.compareBuffersExtended(
                io, diag_v_out, video_out_ref, 0.15, 0.02,
            ) catch |err| {
                std.log.err("DIAG video proj on ref x_in failed: {}", .{err});
                return error.ParityCheckFailed;
            };
            logMetrics("DIAG video proj(ref_x_in)", diag_v_m);
        }
        {
            var diag_a_args = try proj_a_exe.args(allocator);
            defer diag_a_args.deinit(allocator);
            var diag_a_results = try proj_a_exe.results(allocator);
            defer diag_a_results.deinit(allocator);
            diag_a_args.set(.{ proj_a_x_ref, a_emb_ts_buf, proj_a_bufs });
            proj_a_exe.call(diag_a_args, &diag_a_results);
            var diag_a_out = diag_a_results.get(zml.Buffer);
            defer diag_a_out.deinit();

            const diag_a_m = check_utils.compareBuffersExtended(
                io, diag_a_out, audio_out_ref, 0.15, 0.02,
            ) catch |err| {
                std.log.err("DIAG audio proj on ref x_in failed: {}", .{err});
                return error.ParityCheckFailed;
            };
            logMetrics("DIAG audio proj(ref_x_in)", diag_a_m);
        }
    }

    // ---- Run output projection ----
    std.log.info("Running output projection...", .{});

    // Video
    var proj_v_args = try proj_v_exe.args(allocator);
    defer proj_v_args.deinit(allocator);
    var proj_v_results = try proj_v_exe.results(allocator);
    defer proj_v_results.deinit(allocator);
    proj_v_args.set(.{ h_v, v_emb_ts_buf, proj_v_bufs });
    proj_v_exe.call(proj_v_args, &proj_v_results);
    var video_out = proj_v_results.get(zml.Buffer);
    defer video_out.deinit();

    // Audio
    var proj_a_args = try proj_a_exe.args(allocator);
    defer proj_a_args.deinit(allocator);
    var proj_a_results = try proj_a_exe.results(allocator);
    defer proj_a_results.deinit(allocator);
    proj_a_args.set(.{ h_a, a_emb_ts_buf, proj_a_bufs });
    proj_a_exe.call(proj_a_args, &proj_a_results);
    var audio_out = proj_a_results.get(zml.Buffer);
    defer audio_out.deinit();

    // Free block chain outputs
    h_v.deinit();
    h_a.deinit();

    std.log.info("Output projection complete.", .{});

    // ---- Compare results ----
    // atol=0.25: bf16 rounding diverges between XLA/PJRT and PyTorch compilers
    // (different operation fusion/ordering), accumulating across 48 serial blocks.
    // Experimentally confirmed: GPU vs CPU makes no difference, and f32 residuals
    // make things *worse* (diverges further from the reference bf16 path).
    // cos_sim is the primary correctness signal (~0.998 consistently).
    const video_metrics = check_utils.compareBuffersExtended(
        io, video_out, video_out_ref, 0.25, 0.02,
    ) catch |err| {
        std.log.err("Video output comparison failed: {}", .{err});
        return error.ParityCheckFailed;
    };
    logMetrics("video_out", video_metrics);

    const audio_metrics = check_utils.compareBuffersExtended(
        io, audio_out, audio_out_ref, 0.25, 0.02,
    ) catch |err| {
        std.log.err("Audio output comparison failed: {}", .{err});
        return error.ParityCheckFailed;
    };
    logMetrics("audio_out", audio_metrics);

    const video_ok = video_metrics.close_fraction >= 0.99 and video_metrics.cosine_similarity >= 0.995;
    const audio_ok = audio_metrics.close_fraction >= 0.99 and audio_metrics.cosine_similarity >= 0.995;

    if (video_ok and audio_ok) {
        std.log.info("PASSED: both video and audio outputs match.", .{});
    } else {
        std.log.err("FAILED: video_ok={} audio_ok={}", .{ video_ok, audio_ok });
        return error.ParityCheckFailed;
    }
}

fn loadBuf(
    allocator: std.mem.Allocator,
    io: std.Io,
    platform: *zml.Platform,
    store: *zml.io.TensorStore,
    key: []const u8,
    sharding: zml.sharding.Sharding,
) !zml.Buffer {
    return check_utils.loadBufferFromStore(allocator, io, platform, store, key, sharding) catch |err| {
        std.log.err("Missing fixture key: {s}", .{key});
        return err;
    };
}

fn logMetrics(label: []const u8, m: check_utils.ExtendedCompareMetrics) void {
    std.log.info("{s}:  mean_abs={d:.5}  max_abs={d:.5}  cos_sim={d:.6}  close={d:.4}", .{
        label, m.mean_abs_error, m.max_abs_error, m.cosine_similarity, m.close_fraction,
    });
    std.log.info("{s}:  p50={d:.5}  p90={d:.5}  p99={d:.5}  p999={d:.5}", .{
        label, m.abs_err_p50, m.abs_err_p90, m.abs_err_p99, m.abs_err_p999,
    });
}
