/// Live-capture parity checker: AdaLayerNormSingle + OutputProjection.
///
/// Verifies both the 8 AdaLayerNormSingle modules and both OutputProjection
/// streams (video + audio) against the live-pipeline fixture generated by
/// export_live_capture_fixture.py.  Unlike the synthetic-fixture checkers,
/// the inputs here are *real denoising-step activations* from a full pipeline
/// forward pass, giving much stronger validation.
///
/// Usage (step 0, default token-limited fixture):
///   bazel run //examples/ltx:live_capture_check -- \
///       /root/models/ltx-2.3/ltx-2.3-22b-distilled.safetensors \
///       /root/repos/LTX-2/trace_run/live_capture_fixture_step_000.safetensors
///
///   # With a token-limited fixture:
///   bazel run //examples/ltx:live_capture_check -- \
///       /root/models/ltx-2.3/ltx-2.3-22b-distilled.safetensors \
///       /root/repos/LTX-2/trace_run/live_capture_fixture_step_000_t512.safetensors

const std = @import("std");
const zml = @import("zml");
const model = @import("model.zig");
const check_utils = @import("check_utils.zig");

comptime {
    @setEvalBranchQuota(30000);
}

pub const std_options: std.Options = .{ .log_level = .info };

// ---------------------------------------------------------------------------
// Module descriptors
// ---------------------------------------------------------------------------

const AdalnDesc = struct {
    /// Attribute name on velocity_model and prefix in fixture keys.
    attr: []const u8,
    /// Checkpoint key suffix under model.diffusion_model.
    ckpt_suffix: []const u8,
};

const ADALN_MODULES = [_]AdalnDesc{
    .{ .attr = "adaln_single",                            .ckpt_suffix = "adaln_single" },
    .{ .attr = "audio_adaln_single",                      .ckpt_suffix = "audio_adaln_single" },
    .{ .attr = "prompt_adaln_single",                     .ckpt_suffix = "prompt_adaln_single" },
    .{ .attr = "audio_prompt_adaln_single",               .ckpt_suffix = "audio_prompt_adaln_single" },
    .{ .attr = "av_ca_video_scale_shift_adaln_single",    .ckpt_suffix = "av_ca_video_scale_shift_adaln_single" },
    .{ .attr = "av_ca_audio_scale_shift_adaln_single",    .ckpt_suffix = "av_ca_audio_scale_shift_adaln_single" },
    .{ .attr = "av_ca_a2v_gate_adaln_single",             .ckpt_suffix = "av_ca_a2v_gate_adaln_single" },
    .{ .attr = "av_ca_v2a_gate_adaln_single",             .ckpt_suffix = "av_ca_v2a_gate_adaln_single" },
};

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    std.log.info("Live-capture parity checker: AdaLayerNormSingle + OutputProjection", .{});

    var it = init.minimal.args.iterate();
    _ = it.next(); // exe

    const ckpt_path = it.next() orelse {
        std.log.err(
            "Usage: live_capture_check <checkpoint.safetensors> <live_capture_fixture.safetensors>",
            .{},
        );
        return error.InvalidArgs;
    };
    const fixture_path = it.next() orelse {
        std.log.err(
            "Usage: live_capture_check <checkpoint.safetensors> <live_capture_fixture.safetensors>",
            .{},
        );
        return error.InvalidArgs;
    };

    // Open checkpoint
    var ckpt_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, ckpt_path) catch |err| {
        std.log.err("Failed to open checkpoint: {s}", .{ckpt_path});
        return err;
    };
    defer ckpt_reg.deinit();
    var ckpt_store: zml.io.TensorStore = .fromRegistry(allocator, &ckpt_reg);
    defer ckpt_store.deinit();

    // Open fixture
    var fix_reg = zml.safetensors.TensorRegistry.fromPath(allocator, io, fixture_path) catch |err| {
        std.log.err("Failed to open fixture: {s}", .{fixture_path});
        return err;
    };
    defer fix_reg.deinit();
    var fix_store: zml.io.TensorStore = .fromRegistry(allocator, &fix_reg);
    defer fix_store.deinit();

    const platform: *zml.Platform = try .auto(allocator, io, .{});
    defer platform.deinit(allocator);
    const sharding = try zml.sharding.replicatedSharding(platform);

    const root = model.selectTransformerRoot(ckpt_store.view());

    var passes: usize = 0;
    var failures: usize = 0;

    // --- AdaLayerNormSingle checks ---
    inline for (ADALN_MODULES) |m| {
        if (checkAdalnModule(allocator, io, platform, sharding, root, &ckpt_store, &fix_store, m)) |ok| {
            if (ok) passes += 1 else failures += 1;
        } else |err| {
            std.log.err("adaln module {s} raised error: {}", .{ m.attr, err });
            failures += 1;
        }
    }

    // --- OutputProjection checks ---
    if (checkOutputProjection(
        allocator, io, platform, sharding,
        root, &ckpt_store, &fix_store,
        "video", "scale_shift_table", "proj_out",
    )) |ok| {
        if (ok) passes += 1 else failures += 1;
    } else |err| {
        std.log.err("output_projection video raised error: {}", .{err});
        failures += 1;
    }

    if (checkOutputProjection(
        allocator, io, platform, sharding,
        root, &ckpt_store, &fix_store,
        "audio", "audio_scale_shift_table", "audio_proj_out",
    )) |ok| {
        if (ok) passes += 1 else failures += 1;
    } else |err| {
        std.log.err("output_projection audio raised error: {}", .{err});
        failures += 1;
    }

    std.log.info("Results: {d} passed, {d} failed  (total {d})", .{
        passes, failures, passes + failures,
    });
    if (failures > 0) return error.ParityCheckFailed;
}

// ---------------------------------------------------------------------------
// Helper: load a Buffer from the fixture store, with a clear error message.
// ---------------------------------------------------------------------------

fn loadFixtureBuf(
    allocator: std.mem.Allocator,
    io: std.Io,
    platform: *zml.Platform,
    store: *zml.io.TensorStore,
    key: []const u8,
    sharding: zml.sharding.Sharding,
) !zml.Buffer {
    return check_utils.loadBufferFromStore(allocator, io, platform, store, key, sharding) catch |err| {
        std.log.err("Missing fixture key: {s}", .{key});
        return err;
    };
}

// ---------------------------------------------------------------------------
// AdaLayerNormSingle check
// ---------------------------------------------------------------------------

fn checkAdalnModule(
    allocator: std.mem.Allocator,
    io: std.Io,
    platform: *zml.Platform,
    sharding: zml.sharding.Sharding,
    root: zml.io.TensorStore.View,
    ckpt_store: *zml.io.TensorStore,
    fix_store: *zml.io.TensorStore,
    comptime m: AdalnDesc,
) !bool {
    std.log.info("--- Checking adaln {s} (live) ---", .{m.attr});

    // Live fixture keys: "{attr}.sigma_scaled", "{attr}.modulation", "{attr}.embedded_timestep"
    var sigma_buf = try loadFixtureBuf(
        allocator, io, platform, fix_store,
        m.attr ++ ".sigma_scaled", sharding,
    );
    defer sigma_buf.deinit();
    var mod_ref_buf = try loadFixtureBuf(
        allocator, io, platform, fix_store,
        m.attr ++ ".modulation", sharding,
    );
    defer mod_ref_buf.deinit();
    var emb_ref_buf = try loadFixtureBuf(
        allocator, io, platform, fix_store,
        m.attr ++ ".embedded_timestep", sharding,
    );
    defer emb_ref_buf.deinit();

    std.log.info("  sigma: {any}  modulation: {any}  embedded_timestep: {any}", .{
        sigma_buf.shape(), mod_ref_buf.shape(), emb_ref_buf.shape(),
    });

    // sigma shape from fixture: [B] f32.  forwardAdalnSingle tags it .b internally.
    const sigma_tensor = zml.Tensor.fromShape(sigma_buf.shape());

    var params_shape = model.AdaLayerNormSingle.initParams(root.withPrefix(m.ckpt_suffix));

    std.log.info("  Compiling...", .{});
    var exe = try platform.compileFn(
        allocator, io,
        model.forwardAdalnSingle,
        .{ sigma_tensor, params_shape },
        .{ .shardings = &.{sharding} },
    );
    defer exe.deinit();
    std.log.info("  Done", .{});

    var params_bufs = try zml.io.load(
        model.AdaLayerNormSingle.Params,
        &params_shape,
        allocator, io, platform,
        .{
            .store = ckpt_store,
            .shardings = &.{sharding},
            .parallelism = 4,
            .dma_chunks = 4,
            .dma_chunk_size = 16 * zml.MiB,
        },
    );
    defer model.AdaLayerNormSingle.Params.unloadBuffers(&params_bufs);

    var args = try exe.args(allocator);
    defer args.deinit(allocator);
    var results = try exe.results(allocator);
    defer results.deinit(allocator);

    args.set(.{ sigma_buf, params_bufs });
    exe.call(args, &results);

    const AdalnOut = struct { modulation: zml.Buffer, embedded_timestep: zml.Buffer };
    const out = results.get(AdalnOut);
    defer {
        var mb = out.modulation;
        mb.deinit();
        var eb = out.embedded_timestep;
        eb.deinit();
    }

    const mod_stats = check_utils.compareBuffersExtended(
        io, out.modulation, mod_ref_buf, 0.15, 0.02,
    ) catch |err| {
        std.log.err("  modulation comparison error: {}", .{err});
        return false;
    };
    const emb_stats = check_utils.compareBuffersExtended(
        io, out.embedded_timestep, emb_ref_buf, 0.15, 0.02,
    ) catch |err| {
        std.log.err("  embedded_timestep comparison error: {}", .{err});
        return false;
    };

    std.log.info("  modulation:        mean_abs={d:.5}  max_abs={d:.5}  cos_sim={d:.6}  close={d:.4}", .{
        mod_stats.mean_abs_error, mod_stats.max_abs_error,
        mod_stats.cosine_similarity, mod_stats.close_fraction,
    });
    std.log.info("  embedded_timestep: mean_abs={d:.5}  max_abs={d:.5}  cos_sim={d:.6}  close={d:.4}", .{
        emb_stats.mean_abs_error, emb_stats.max_abs_error,
        emb_stats.cosine_similarity, emb_stats.close_fraction,
    });

    const mod_ok = mod_stats.close_fraction >= 0.999 and mod_stats.mean_abs_error < 0.1;
    const emb_ok = emb_stats.close_fraction >= 0.999 and emb_stats.mean_abs_error < 0.1;

    if (mod_ok and emb_ok) {
        std.log.info("  {s}: PASSED", .{m.attr});
        return true;
    }
    std.log.err("  {s}: FAILED (mod_ok={} emb_ok={})", .{ m.attr, mod_ok, emb_ok });
    return false;
}

// ---------------------------------------------------------------------------
// OutputProjection check
// ---------------------------------------------------------------------------

fn checkOutputProjection(
    allocator: std.mem.Allocator,
    io: std.Io,
    platform: *zml.Platform,
    sharding: zml.sharding.Sharding,
    root: zml.io.TensorStore.View,
    ckpt_store: *zml.io.TensorStore,
    fix_store: *zml.io.TensorStore,
    comptime stream: []const u8,     // "video" or "audio"
    comptime sst_key: []const u8,    // "scale_shift_table" or "audio_scale_shift_table"
    comptime proj_prefix: []const u8, // "proj_out" or "audio_proj_out"
) !bool {
    const fix_prefix = "output_projection." ++ stream;
    std.log.info("--- Checking output_projection.{s} (live) ---", .{stream});

    var x_buf = try loadFixtureBuf(
        allocator, io, platform, fix_store,
        fix_prefix ++ ".x_in", sharding,
    );
    defer x_buf.deinit();
    var emb_buf = try loadFixtureBuf(
        allocator, io, platform, fix_store,
        fix_prefix ++ ".embedded_timestep", sharding,
    );
    defer emb_buf.deinit();
    var ref_buf = try loadFixtureBuf(
        allocator, io, platform, fix_store,
        fix_prefix ++ ".output", sharding,
    );
    defer ref_buf.deinit();

    std.log.info("  x_in: {any}  embedded_timestep: {any}  output: {any}", .{
        x_buf.shape(), emb_buf.shape(), ref_buf.shape(),
    });

    var params_shape = model.OutputProjection.Params{
        .scale_shift_table = root.createTensor(sst_key, .{ .n_ssv, .d }, null),
        .proj_out = .init(
            root.withPrefix(proj_prefix).createTensor("weight", .{ .d_out, .d }, null),
            root.withPrefix(proj_prefix).createTensor("bias", .{.d_out}, null),
            .d,
        ),
    };

    const x_s = zml.Tensor.fromShape(x_buf.shape()).withPartialTags(.{ .b, .t, .d });
    const emb_s = zml.Tensor.fromShape(emb_buf.shape()).withPartialTags(.{ .b, .d_emb });

    std.log.info("  Compiling...", .{});
    var exe = try platform.compileFn(
        allocator, io,
        model.forwardOutputProjection,
        .{ x_s, emb_s, params_shape },
        .{ .shardings = &.{sharding} },
    );
    defer exe.deinit();
    std.log.info("  Done", .{});

    var params_bufs = try zml.io.load(
        model.OutputProjection.Params,
        &params_shape,
        allocator, io, platform,
        .{
            .store = ckpt_store,
            .shardings = &.{sharding},
            .parallelism = 4,
            .dma_chunks = 4,
            .dma_chunk_size = 16 * zml.MiB,
        },
    );
    defer model.OutputProjection.Params.unloadBuffers(&params_bufs);

    var args = try exe.args(allocator);
    defer args.deinit(allocator);
    var results = try exe.results(allocator);
    defer results.deinit(allocator);

    args.set(.{ x_buf, emb_buf, params_bufs });
    exe.call(args, &results);

    var output_buf = results.get(zml.Buffer);
    defer output_buf.deinit();

    const metrics = check_utils.compareBuffersExtended(
        io, output_buf, ref_buf, 0.15, 0.02,
    ) catch |err| {
        std.log.err("  comparison error: {}", .{err});
        return false;
    };
    const passed = metrics.close_fraction >= 0.999 and metrics.mean_abs_error < 0.1;

    std.log.info("  output:  mean_abs={d:.5}  max_abs={d:.5}  cos_sim={d:.6}  close={d:.4}", .{
        metrics.mean_abs_error, metrics.max_abs_error,
        metrics.cosine_similarity, metrics.close_fraction,
    });

    if (passed) {
        std.log.info("  output_projection.{s}: PASSED", .{stream});
    } else {
        std.log.err("  output_projection.{s}: FAILED", .{stream});
    }
    return passed;
}
