name: ci
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  ci:
    name: ci-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: cpu
            bazel_opts: ""
            self_hosted: false
            run_tests: true
            runner_labels:
              - runs-on
              - runner=16cpu-linux-x64
              - family=c8+c7
              - image=ubuntu24-amd64
              - run-id=${{ github.run_id }}
              - extras=s3-cache
          - target: neuron
            bazel_opts: "--@zml//platforms:neuron=true --@zml//platforms:cpu=false"
            self_hosted: false
            run_tests: false
            runner_labels:
              - runs-on
              - runner=16cpu-linux-x64
              - family=c8+c7
              - image=ubuntu24-amd64
              - run-id=${{ github.run_id }}
              - extras=s3-cache
          - target: tpu
            bazel_opts: "--@zml//platforms:tpu=true --@zml//platforms:cpu=false"
            self_hosted: false
            run_tests: false
            runner_labels:
              - runs-on
              - runner=16cpu-linux-x64
              - family=c8+c7
              - image=ubuntu24-amd64
              - run-id=${{ github.run_id }}
              - extras=s3-cache
          - target: cuda
            bazel_opts: "--@zml//platforms:cuda=true --@zml//platforms:cpu=false"
            self_hosted: true
            run_tests: true
            runner_labels: ["self-hosted", "platform=cuda"]
          - target: rocm
            bazel_opts: "--@zml//platforms:rocm=true --@zml//platforms:cpu=false"
            self_hosted: true
            run_tests: true
            runner_labels: ["self-hosted", "platform=rocm"]
    runs-on: ${{ matrix.runner_labels }}
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure self hosted cache permissions
        if: ${{ matrix.self_hosted }}
        run: mkdir -p /tmp/zig-cache && mkdir -p /tmp/zml && sudo chmod -R 777 /tmp/zig-cache && sudo chmod -R 777 /tmp/zml

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-version: 1.28.1
          bazelisk-cache: ${{ !matrix.self_hosted }}
          repository-cache: ${{ !matrix.self_hosted }}
          external-cache: ${{ !matrix.self_hosted }}
          bazelrc: |
            common --verbose_failures
            common --keep_going
            common --test_output=streamed
            common --color=yes
            common --show_timestamps
            ${{ !matrix.self_hosted && secrets.BUILDBUDDY_CI_API_KEY != '' && 'common --config=remote' || '' }}
            ${{ !matrix.self_hosted && secrets.BUILDBUDDY_CI_API_KEY != '' && format('common:remote --remote_header=x-buildbuddy-api-key={0}', secrets.BUILDBUDDY_CI_API_KEY) || '' }}
            ${{ !matrix.self_hosted && secrets.BUILDBUDDY_CI_API_KEY != '' && 'common:remote --remote_download_outputs=minimal' || '' }}
            ${{ matrix.self_hosted && 'common --disk_cache=/home/actions/.cache/bazel-disk' || '' }}

      - run: bazel mod graph
      - run: bazel query ${{ matrix.bazel_opts }} //...
      - run: bazel build ${{ matrix.bazel_opts }} //...
      - if: ${{ matrix.run_tests }}
        run: bazel test ${{ matrix.bazel_opts }} //...

  lint:
    runs-on:
      [
        "runs-on",
        "runner=4cpu-linux-x64",
        "image=ubuntu24-amd64",
        "run-id=${{ github.run_id }}",
        "extras=s3-cache",
      ]
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
          mirror: https://mirror.zml.ai/zig

      - name: Zig Format
        run: zig fmt --check  $(git ls-files --exclude-standard -- ':!third_party/*' '*.zig' | xargs)

      - name: No autofix in Zig code
        run: bash -c "! git grep -l '// autofix' -- '*.zig'"
