name: ci
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  platforms:
    strategy:
      matrix:
        runtimes:
          - target: cuda
            bazel_opts: "--@zml//platforms:cuda=true --@zml//platforms:cpu=false"
            runs-on: ["self-hosted", "platform=cuda"]
          - target: rocm
            bazel_opts: "--@zml//platforms:rocm=true --@zml//platforms:cpu=false"
            runs-on: ["self-hosted", "platform=rocm"]
    runs-on: ${{ matrix.runtimes.runs-on }}
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure self hosted cache permissions
        run: mkdir -p /tmp/zig-cache && mkdir -p /tmp/zml && sudo chmod -R 777 /tmp/zig-cache && sudo chmod -R 777 /tmp/zml

      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-version: 1.28.1
          bazelisk-cache: false
          # todo: use `--config=debug` instead of `-c opt` when static archive bug is fixed
          bazelrc: |
            common -c opt
            common --verbose_failures
            common --keep_going
            common --test_output=streamed
            common --color=yes
            common --show_timestamps
            common --disk_cache=/home/actions/.cache/bazel-disk
            common --strip=always

      - run: bazel mod explain
      - run: bazel mod graph
      - run: bazel query ${{ matrix.runtimes.bazel_opts }} //...
      - run: bazel build ${{ matrix.runtimes.bazel_opts }} //...
      - run: bazel test ${{ matrix.runtimes.bazel_opts }} //...

  platform-cpu:
    runs-on:
      [
        "runs-on",
        "runner=4cpu-linux-x64",
        "image=ubuntu24-amd64",
        "run-id=${{ github.run_id }}",
        "extras=s3-cache",
      ]
    env:
      BUILDBUDDY_CI_API_KEY: ${{ secrets.BUILDBUDDY_CI_API_KEY }}
      CI_BAZEL_CACHE: ~/.cache/bazel-repo
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v6

      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-version: 1.28.1
          bazelisk-cache: true
          repository-cache: true
          external-cache: true
          bazelrc: |
            common --verbose_failures
            common --keep_going
            common --test_output=streamed
            common --color=yes
            common --show_timestamps
            common --remote_download_outputs=minimal

      - name: Add .github/bin to PATH (remote-bazel)
        run: echo "$GITHUB_WORKSPACE/.github/bin" >> "$GITHUB_PATH"

      - run: remote-bazel mod explain
      - run: remote-bazel mod graph
      - run: remote-bazel query //...
      - run: remote-bazel build //...
      - run: remote-bazel test //...

  zig-lint:
    runs-on:
      [
        "runs-on",
        "runner=4cpu-linux-x64",
        "image=ubuntu24-amd64",
        "run-id=${{ github.run_id }}",
        "extras=s3-cache",
      ]
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
          mirror: https://mirror.zml.ai/zig

      - name: Zig Format
        run: zig fmt --check  $(git ls-files --exclude-standard -- ':!third_party/*' '*.zig' | xargs)

      - name: No autofix in Zig code
        run: bash -c "! git grep -l '// autofix' -- '*.zig'"
